/* ============ HISTOIRES CM2 (10) — monde « Légende du ranch » 🌟 ============
   Textes originaux (Caramel 2), niveau CM2 : 186 à 190 mots, phrases longues et variées,
   ponctuation expressive, une vraie petite intrigue (problème → péripéties → résolution).
   lvl 4,0 → 4,9 · cible de Zip 102 → 120 mots/min · need 60 → 85 ⭐.
   Contraintes (vérifiées par tests/stories.test.mjs) :
   - lus à voix haute : ni apostrophe, ni trait d'union, ni chiffre, ni guillemets, ni tiret de dialogue ;
     donc aucune élision possible : jamais « de », « que », « si », « ne », « le », « la », « se »
     devant une voyelle, un h muet ou un jeton (le prénom peut commencer par une voyelle) ;
   - chaque mot appartient au lexique du modèle Vosk (tests/lexicon.mjs) : pas de « ranch »
     (absent du lexique), on dit « la ferme » ;
   - accords : le héros n'a que {El}/{el}/{fiere}, la monture {IlM}/{ilM}/{leM}/{sonM}/{duM} et
     {contentM}{surprisM}{legerM}{rassureM}{fascineM}. Tout autre adjectif ou participe qui
     s'accorderait avec eux est reformulé ; le duo n'est jamais repris par « ils », « eux »,
     « tous », « amis » (une fille et une licorne → « elles ») : on écrit « {P} et {N} »,
     « la petite équipe », « les deux complices », « le duo » ;
   - rien ne suppose un cheval (sabot, crinière, hennir, galop, selle, pattes, queue) :
     le compagnon peut être un chat, un dauphin, un dragon… */

export const CM2_STORIES = [
  { id:'cm2-abeilles', emoji:'🐝', title:'Les abeilles du printemps', target:102, need:60, lvl:4, world:'legende',
    theme:{ sky:['#bae6fd','#e0f2fe'], ground:['#bbf7d0','#4ade80'], obstacle:'🌼',
      decos:[{e:'☀️',x:88,top:5,s:1.5},{e:'🌳',x:8,top:18,s:2},{e:'🐝',top:12,s:1,drift:26},{e:'🌸',x:38,bot:6,s:.9},{e:'🍯',x:66,bot:5,s:1}] },
    text:"Ce matin de printemps, une drôle de nouvelle court dans le village : les abeilles du vieux Marcel ont quitté leur ruche ! Sans elles, pas de miel cet été, et peu de fruits dans les vergers. {P} part aussitôt à leur recherche avec {N}. Dans la prairie, aucune abeille ne vole de fleur en fleur. Soudain, {N} tend la tête vers la forêt : un bourdonnement léger flotte dans le vent. Les deux complices suivent ce chant mystérieux et entrent sous les grands arbres. Là, à une branche de tilleul, pend une énorme grappe vivante et dorée : des milliers de petites abeilles serrées les unes contre les autres ! {P} reste à distance pour ne pas les effrayer, et {N} file au village chercher Marcel. Bientôt, le vieil homme arrive avec un panier en osier. Doucement, il secoue la branche, et toute la grappe glisse dans le panier comme une pluie de miel. Le soir même, les abeilles dorment dans une ruche toute neuve. Pour remercier la petite équipe, Marcel offre à {P} un pot de miel doré, et {N} reçoit la première fleur de pommier de la saison, comme une médaille." },
  { id:'cm2-moulin', emoji:'🌾', title:'Le moulin silencieux', target:104, need:62, lvl:4.1, world:'legende',
    theme:{ sky:['#93c5fd','#dbeafe'], ground:['#fde047','#ca8a04'], obstacle:'🌾',
      decos:[{e:'☀️',x:12,top:6,s:1.5},{e:'🏡',x:82,top:18,s:1.8},{e:'🦆',top:20,s:1,drift:40},{e:'🍞',x:56,bot:5,s:1},{e:'🌾',x:24,bot:6,s:1.1}] },
    text:"La veille de la fête des moissons, la grande roue du moulin cesse de tourner ! Sans farine, le boulanger ne pourra pas cuire le pain géant que tout le village attend. Le meunier se gratte la tête, inquiet ; le ruisseau qui fait tourner sa roue ressemble à un mince filet. {P} et {N} décident de remonter le courant pour percer ce mystère. Plus haut, derrière un bosquet de saules, {N} découvre la réponse : un mur de branches et de boue barre le ruisseau ! Au sommet, deux castors les observent avec méfiance. Détruire leur maison ? Jamais ! {P} réfléchit, puis une idée lui vient : creuser une petite rigole sur le côté, pour laisser passer le courant sans abîmer le barrage. Aussitôt, {P} se met au travail avec une vieille pelle, et {N} pousse les cailloux un par un. Bientôt, le ruisseau contourne le barrage et repart en chantant vers le village ! En bas, la roue se remet à tourner. Le lendemain, au milieu de la place, trône un pain énorme et doré. Sur sa croûte, le boulanger a dessiné un petit castor, et le premier morceau est pour {P} et {N}." },
  { id:'cm2-pie', emoji:'🔍', title:'La voleuse de trésors', target:106, need:64, lvl:4.2, world:'legende',
    theme:{ sky:['#fde68a','#fef3c7'], ground:['#bef264','#65a30d'], obstacle:'🔑',
      decos:[{e:'🌳',x:84,top:16,s:2.1},{e:'🪶',top:10,s:1,drift:24},{e:'🔍',x:10,top:10,s:1.2},{e:'🥄',x:40,bot:5,s:.9},{e:'💍',x:64,bot:6,s:.9}] },
    text:"Depuis une semaine, de drôles de choses se passent à la ferme. Lundi, la cuillère en argent a disparu ; mardi, les clés du tracteur ; mercredi, la médaille du dernier concours. Qui peut bien jouer à ce jeu ? {P} décide de mener son enquête avec {N}. Sur le rebord de la fenêtre, {N} trouve un premier indice : une longue plume noire et blanche. {P} remarque aussi un détail curieux : tous les objets disparus brillent au soleil. Le lendemain, les deux détectives se cachent derrière une botte de foin. Soudain, un éclair noir et blanc traverse la cour, se pose sur la table du jardin et emporte le dé à coudre de la fermière. La voleuse est démasquée : une pie ! {P} et {N} la suivent à travers le verger, vers le grand peuplier. Tout en haut, dans son nid, brillent mille trésors : la cuillère, les clés, la médaille, et même une bague perdue depuis des années ! Le fermier récupère chaque objet en riant de bon cœur. Pour ne pas fâcher la pie, {P} dépose dans son nid trois boutons dorés. Depuis, chaque matin, la petite voleuse vient saluer {N} sur la barrière." },
  { id:'cm2-phoque', emoji:'🦭', title:'{N} et le petit phoque', target:108, need:67, lvl:4.3, world:'legende',
    theme:{ sky:['#7dd3fc','#e0f2fe'], ground:['#fde68a','#fbbf24'], obstacle:'🐚',
      decos:[{e:'☀️',x:88,top:5,s:1.5},{e:'🌊',top:24,s:1.2,drift:34},{e:'🐦',top:10,s:1,drift:28},{e:'🪨',x:14,bot:6,s:1.2},{e:'🦭',x:68,bot:5,s:1.4}] },
    text:"Ce matin, la mer est très basse, et la plage semble immense. {P} et {N} se promènent entre les rochers couverts de varech. Soudain, un petit cri plaintif se fait entendre. Dans une flaque tiède, un bébé phoque les regarde avec de grands yeux noirs. Aucune maman en vue, et la mer est encore loin ! {P} voudrait le porter vers les vagues, mais {el} se souvient des conseils du gardien de la baie : il ne faut jamais toucher un bébé phoque, car sa mère pourrait le rejeter. {N} file prévenir le gardien, et {P} reste à distance pour veiller sur le petit. Bientôt, un chien curieux arrive en courant, suivi de son maître ; {P} explique la situation, et le promeneur rappelle son chien. Enfin, le gardien est là. Il observe le petit phoque et rassure tout le monde : la mère pêche sans doute au large, et elle reviendra avec la marée. Peu à peu, la mer remonte, et les vagues atteignent la flaque. Le bébé plonge aussitôt, et une tête ronde surgit tout près : sa maman ! {P} sourit : parfois, pour aider, il suffit de savoir attendre." },
  { id:'cm2-chevreau', emoji:'🐐', title:'Le chevreau égaré', target:110, need:70, lvl:4.4, world:'legende',
    theme:{ sky:['#94a3b8','#cbd5e1'], ground:['#86efac','#15803d'], obstacle:'🪨',
      decos:[{e:'🏔️',x:8,top:8,s:2.2},{e:'⛈️',x:70,top:6,s:1.4},{e:'☁️',top:12,s:1.4,drift:30},{e:'🐐',x:54,bot:5,s:1.2},{e:'🔔',x:86,top:24,s:1}] },
    text:"Cet été, {P} et {N} passent quelques jours chez la bergère, dans la montagne. Un soir, de lourds nuages gris couvrent les sommets, et la bergère rassemble son troupeau. Mais, en comptant ses chèvres, elle pousse un cri : Flocon, le plus jeune chevreau, a disparu ! Aussitôt, {P} et {N} remontent le sentier en criant son nom. Le vent siffle entre les rochers, et les premières gouttes tombent déjà. Près du torrent, {N} se fige et écoute : un faible bêlement monte derrière un buisson épineux. Le pauvre chevreau est prisonnier des ronces, et plus il se débat, plus les épines le retiennent. {P} lui parle doucement, puis écarte les branches une à une. Enfin libre, Flocon tremble encore ; {P} le serre contre son cœur. Il faut redescendre, et vite, car le tonnerre gronde sur les crêtes. Dans la brume, le chemin disparaît presque. Heureusement, le tintement des clochettes du troupeau guide la petite équipe vers le chalet. Quand Flocon retrouve sa mère, la bergère essuie une larme de joie. Plus tard, autour du feu, elle offre à {P} un bol de lait chaud, et à {N} une belle pomme rouge." },
  { id:'cm2-brouillard', emoji:'🌫️', title:'Le chemin dans le brouillard', target:112, need:73, lvl:4.5, world:'legende',
    theme:{ sky:['#d6d3d1','#e7e5e4'], ground:['#a16207','#713f12'], obstacle:'🍄',
      decos:[{e:'🌫️',top:10,s:1.6,drift:40},{e:'🌲',x:8,top:18,s:2},{e:'🔔',x:84,top:8,s:1.2},{e:'🍂',x:34,bot:6,s:1},{e:'🌰',x:60,bot:5,s:1}] },
    text:"En automne, la forêt se couvre de mille couleurs. Un matin, {P} et {N} partent ramasser des châtaignes. Leur panier se remplit si vite que la petite équipe ne voit pas le temps passer. Mais, peu à peu, une brume épaisse se glisse entre les troncs. Bientôt, impossible de distinguer le sentier : tous les arbres se ressemblent, gris et silencieux, comme des fantômes. {P} sent son cœur battre plus fort. Où est donc la ferme ? Heureusement, {el} se rappelle les conseils du vieux garde forestier : quand on se perd, il ne faut pas courir au hasard ; il faut écouter, puis suivre le ruisseau qui descend vers la vallée. Alors {P} et {N} restent immobiles et écoutent. Un petit clapotis chante sous les fougères. Le duo suit le ruisseau entre les pierres moussues. Plus bas, un autre son traverse la brume : la cloche du village sonne six coups. Grâce à ce chant familier, {P} et {N} retrouvent enfin la lisière de la forêt. Là, le brouillard se déchire, et les fenêtres de la ferme brillent dans le soir. Plus tard, devant la cheminée, les châtaignes grillées éclatent dans la poêle." },
  { id:'cm2-citrouille', emoji:'🎃', title:'La citrouille du concours', target:114, need:76, lvl:4.6, world:'legende',
    theme:{ sky:['#fed7aa','#ffedd5'], ground:['#bef264','#84cc16'], obstacle:'🎃',
      decos:[{e:'☀️',x:88,top:5,s:1.7},{e:'🐝',top:12,s:1,drift:30},{e:'🌻',x:10,bot:6,s:1.2},{e:'🪣',x:40,bot:5,s:1},{e:'🎃',x:70,bot:5,s:1.4}] },
    text:"Au printemps, {P} a planté une graine de citrouille dans le potager, avec un rêve fou : gagner le grand concours de la foire. Chaque jour, {N} surveille la petite pousse, qui grandit, grimpe et déploie de larges feuilles. Mais en été, une terrible chaleur écrase la campagne. Pas une goutte de pluie pendant des semaines ! Le puits de la ferme est presque à sec, et les feuilles de la citrouille pendent tristement. {P} a une idée : pour garder la fraîcheur, {el} recouvre la terre de paille. Puis, chaque matin, {P} et {N} montent à la source et rapportent deux seaux pleins. La petite équipe arrose aussi le jardin de la vieille Rose, qui ne peut plus porter de lourdes charges. Le jour de la foire, la citrouille du potager paraît bien modeste à côté de celle du fermier voisin, énorme comme une brouette ! Pourtant, quand le jury apprend comment cette citrouille a survécu à la sécheresse, et comment Rose a sauvé ses tomates grâce à {P} et à {N}, il décerne un prix spécial : le ruban du courage ! Le soir, la citrouille devient une soupe délicieuse pour tout le village." },
  { id:'cm2-grotte', emoji:'💎', title:'La grotte aux cristaux', target:116, need:79, lvl:4.7, world:'legende',
    theme:{ sky:['#334155','#1e293b'], ground:['#78716c','#44403c'], obstacle:'💎',
      decos:[{e:'💎',x:20,top:12,s:1.1},{e:'🔦',x:80,top:10,s:1.3},{e:'✨',top:16,s:1,drift:22},{e:'🪨',x:36,bot:6,s:1.2},{e:'🕯️',x:60,bot:5,s:1.1}] },
    text:"Tout le monde connaît la légende : derrière la cascade se cache une grotte dont les murs brillent comme un ciel étoilé. Gaspard, le vieux guide du village, propose à {P} et à {N} de la découvrir. Gaspard prend sa grosse lampe, {P} une plus petite, puis le trio entre dans la montagne. À chaque carrefour, {P} trace une flèche à la craie sur la roche, par prudence. Enfin, une immense salle apparaît : des milliers de cristaux étincellent, violets, roses ou transparents comme de la glace. {N} admire ce spectacle, {fascineM}. Soudain, une goutte glacée tombe sur la grosse lampe : elle grésille, puis cesse de briller. La petite lampe faiblit à son tour : le noir devient total. Pas de panique ! Gaspard allume une bougie de secours. Dans cette faible lueur, les flèches blanches tracées par {P} se mettent à briller sur la roche. Une flèche, puis une autre, puis une autre encore : le chemin se dessine. Un souffle frais caresse leur visage, et le bruit de la cascade grandit. La sortie ! Dehors, Gaspard félicite {P} pour sa prudence et lui offre un petit cristal violet, en souvenir de ce voyage." },
  { id:'cm2-neige', emoji:'🛷', title:'La maison sous la neige', target:118, need:82, lvl:4.8, world:'legende',
    theme:{ sky:['#e2e8f0','#f8fafc'], ground:['#f1f5f9','#cbd5e1'], obstacle:'🪵',
      decos:[{e:'🌨️',x:12,top:6,s:1.3},{e:'❄️',top:10,s:1,drift:26},{e:'🌲',x:46,top:20,s:1.6},{e:'🏠',x:80,top:16,s:1.7},{e:'🛷',x:24,bot:5,s:1.2}] },
    text:"Toute la nuit, une tempête de neige a soufflé sur la vallée. Au matin, la ferme disparaît sous un épais manteau blanc. {P} observe la colline où vit la vieille Jeanne, toute seule. {El} remarque soudain un détail inquiétant : la cheminée de Jeanne ne fume pas. Aussitôt, {P} charge un traîneau de bois sec, de soupe chaude et de pain. {N} tire le traîneau dans la neige profonde, et {P} pousse derrière de toutes ses forces. Le vent glacé fouette leurs visages ; chaque pas demande un effort immense. Enfin, Jeanne ouvre sa porte, enveloppée dans trois châles, les mains bleues de froid. Son tas de bois est enfoui sous la neige, et son poêle est éteint depuis la veille. {P} allume un bon feu, pendant que la soupe chauffe. Une douce chaleur remplit la pièce, et les joues de Jeanne retrouvent leurs couleurs. Pour dire merci, la vieille dame raconte les hivers de son enfance : les loups dans la forêt, les veillées au coin du feu, les parties de luge sur le lac gelé. Le soir, le tracteur du voisin dégage la route, et tout le village monte saluer Jeanne." },
  { id:'cm2-lanternes', emoji:'🏮', title:'La fête des lanternes', target:120, need:85, lvl:4.9, world:'legende',
    theme:{ sky:['#1e1b4b','#312e81'], ground:['#1e3a8a','#172554'], obstacle:'🏮',
      decos:[{e:'🌕',x:84,top:6,s:1.6},{e:'⭐',x:34,top:6,s:.9},{e:'🏮',x:12,top:12,s:1.3},{e:'🏮',x:56,top:20,s:1.1},{e:'✨',top:14,s:1,drift:24}] },
    text:"Chaque été, pendant la nuit la plus courte, le village dépose des centaines de lanternes sur le lac. Ces merveilles de papier, le vieil Augustin les fabrique depuis toujours. Mais cette année, il a glissé de son échelle et porte un bras dans le plâtre : pas une lanterne ne sera prête ! {P} refuse de baisser les bras. Avec {N}, {el} rend visite au vieil artisan, qui accepte de tout leur apprendre : plier le papier, courber le fil de fer, fixer la bougie. Au début, rien ne marche : le papier se déchire, la colle refuse de tenir, une lanterne penche comme une tour fatiguée. Mais, à force de patience, les lanternes se multiplient. Le grand soir, un vent violent menace de les faire chavirer. Abandonner, si près du but ? Certainement pas ! Vers minuit, le vent tombe enfin, et le lac devient lisse comme un miroir. Une à une, les lanternes glissent sur les eaux noires et dessinent un long fleuve de lumière. Augustin regarde le spectacle, les yeux brillants de larmes. Puis il annonce à la foule : désormais, la fête des lanternes sera confiée à {P} et à {N} !" }
];
