/* ============ HISTOIRES v11 (27) — « La course de Caramel » ============
   Copie VERBATIM du tableau STORIES de la v11.3 (commit c5bd8d1, index.html) : mêmes ids
   (les ⭐ migrées y sont attachées), emoji, titres, cibles de Zip, paliers need, décors et textes,
   au caractère près (vérifié par tests/stories.test.mjs). Seul le champ v11 « best » disparaît
   (les ⭐ vivent dans profile.wallet.stars) ; deux champs s'ajoutent :
     lvl   = niveau absolu A de lecture (0 = rentrée CP … 5 = fin CM2, cf. core/levels.js) ;
     world = monde de la carte (cf. WORLDS dans ./index.js).
   Textes lus à voix haute : ni apostrophe ni trait d'union (contrainte reco vocale, CDC v11 §8).
   Jetons de template : {P} héros · {N} compagnon · {leM}/{LeM}/{sonM}/{SonM}/{duM} · {ilM}/{IlM}
   {El}/{el}/{fiere} (genre du héros) · {contentM}{surprisM}{legerM}{rassureM}{fascineM} (genre de la monture).
   NE PAS MODIFIER les textes : toute retouche casserait la parité v11 (et les ⭐ déjà gagnées). */

export const LEGACY_STORIES = [
  /* ---------- Premiers galops 🐣 (ex-CE1 v11) · lvl 1,2 → 1,7 ---------- */
  { id:'ce1-carotte', emoji:'🥕', title:'La carotte du matin', target:30, need:0, lvl:1.2, world:'galops',
    theme:{ sky:['#7dd3fc','#bae6fd'], ground:['#86efac','#4ade80'], obstacle:'🌿',
      decos:[{e:'☀️',x:88,top:5,s:1.6},{e:'🏡',x:8,top:16,s:1.9},{e:'🐔',x:64,bot:5,s:1},{e:'🥕',x:34,bot:6,s:.9}] },
    text:"{P} ouvre la grande porte de la ferme. {SonM} {N} attend près du pré. {El} lui donne une carotte orange. {N} croque la carotte très fort. {IlM} est {contentM}. Ensuite, {ils} partent jouer dans le pré vert." },
  { id:'ce1-bain', emoji:'🛁', title:'Le grand bain', target:33, need:0, lvl:1.3, world:'galops',
    theme:{ sky:['#bae6fd','#e0f2fe'], ground:['#86efac','#4ade80'], obstacle:'🫧',
      decos:[{e:'☀️',x:88,top:5,s:1.5},{e:'🫧',top:10,s:1.1,drift:26},{e:'🪣',x:70,bot:5,s:1.1},{e:'💦',x:22,top:24,s:1}] },
    text:"Ce matin, {N} est {pleinM} de boue. {P} prépare un grand bain tiède. {El} frotte le dos, les jambes et la tête. {N} secoue tout son corps et envoie des gouttes partout ! {P} rit très fort. Maintenant, {leM} est {toutM} propre et {toutM} {douxM}." },
  { id:'ce1-verger', emoji:'🍏', title:'Les pommes du verger', target:36, need:0, lvl:1.4, world:'galops',
    theme:{ sky:['#93c5fd','#bfdbfe'], ground:['#86efac','#22c55e'], obstacle:'🍏',
      decos:[{e:'🌳',x:10,top:18,s:2},{e:'🌳',x:80,top:20,s:1.8},{e:'🍏',x:46,top:26,s:1},{e:'🐝',top:12,s:1,drift:28}] },
    text:"{P} et {N} vont au verger. Les pommes vertes brillent en haut du grand arbre. {N} tend le cou, mais elles sont trop hautes. Alors {P} grimpe sur son dos et attrape trois belles pommes. {Ils} partagent le goûter, {assisD} sous le soleil doux." },
  { id:'ce1-nuit', emoji:'🌙', title:'Bonne nuit', target:39, need:0, lvl:1.5, world:'galops',
    theme:{ sky:['#312e81','#4c1d95'], ground:['#14532d','#052e16'], obstacle:'⭐',
      decos:[{e:'🌕',x:86,top:6,s:1.6},{e:'⭐',x:20,top:10,s:1},{e:'⭐',x:50,top:16,s:.8},{e:'🦉',x:8,top:22,s:1.2}] },
    text:"La nuit tombe doucement sur la ferme. {N} rentre dans son abri de paille bien chaude. {P} lui raconte une petite histoire de pirates et de trésors. {LeM} ferme les yeux tranquillement. Dehors, la lune ronde veille sur {eux}. Bonne nuit, {N} !" },
  { id:'ce1-flaque', emoji:'💦', title:'La flaque géante', target:42, need:0, lvl:1.6, world:'galops',
    theme:{ sky:['#cbd5e1','#e2e8f0'], ground:['#86efac','#4ade80'], obstacle:'💧',
      decos:[{e:'🌧️',x:12,top:6,s:1.3},{e:'☁️',top:8,s:1.4,drift:36},{e:'💧',x:42,top:24,s:1},{e:'🌈',x:72,top:8,s:1.6}] },
    text:"Il a plu toute la nuit. Une flaque géante brille au milieu du chemin. {N} saute dedans à pieds joints ! {P} reçoit plein de gouttes fraîches et rit aux éclats. Alors {ils} sautent encore, encore et encore, de plus en plus haut. Quelle belle journée !" },
  { id:'ce1-cadeau', emoji:'🎁', title:'La surprise', target:45, need:0, lvl:1.7, world:'galops',
    theme:{ sky:['#fbcfe8','#fce7f3'], ground:['#bbf7d0','#86efac'], obstacle:'🎁',
      decos:[{e:'🎈',x:10,top:8,s:1.2},{e:'🎉',x:50,top:6,s:1},{e:'🎀',x:80,top:12,s:1.1},{e:'🌼',x:30,bot:5,s:.9}] },
    text:"Ce matin, une surprise attend {N} : un gros cadeau rouge est posé sur la paille. {P} tire sur le ruban doré. Dedans, il y a une couverture toute douce et un sac de carottes ! {N} fait un petit saut de joie. Quel beau jour de fête pour toute la ferme !" },

  /* ---------- Petit trot 🌱 (ex-CE2 v11, textes v10 retrofités) ----------
     lvl 2,0 → 3,0 à pas régulier (1/14) sur les 15 histoires ex-CE2 : Petit trot, Grand galop, Champion */
  { id:'pomme', emoji:'🍎', title:'{N} {leM}', target:40, need:0, lvl:2, world:'trot',
    theme:{ sky:['#7dd3fc','#bae6fd'], ground:['#86efac','#4ade80'], obstacle:'🌿',
      decos:[{e:'☀️',x:88,top:5,s:1.6},{e:'☁️',top:6,s:1.4,drift:38},{e:'☁️',top:20,s:1.1,drift:55},{e:'🌼',x:8,bot:6,s:1},{e:'🌻',x:68,bot:5,s:1.1}] },
    text:"{P} arrive à la ferme ce matin. {SonM} {N} attend près de la barrière. {El} brosse {sonM} doucement et lui donne une pomme bien rouge. {N} remue la queue car {ilM} est {contentM}. Ensuite, {P} pose la selle et met son casque pour la promenade." },
  { id:'foret', emoji:'🌳', title:'Promenade en forêt', target:44, need:0, lvl:2.07, world:'trot',
    theme:{ sky:['#93c5fd','#bfdbfe'], ground:['#4ade80','#16a34a'], obstacle:'🌿',
      decos:[{e:'🌳',x:6,top:24,s:1.9},{e:'🌲',x:84,top:22,s:1.9},{e:'🐦',top:10,s:1,drift:30},{e:'🍄',x:58,bot:5,s:.9}] },
    text:"Ce matin, {P} monte sur {N} pour une balade dans la forêt. Les oiseaux chantent et les feuilles dansent avec le vent. {LeM} trotte sur le petit chemin plein de fleurs. Soudain, un lapin gris traverse devant {eux}. {N} reste très calme et {P} félicite {sonM} avec une caresse." },
  { id:'cirque', emoji:'🎪', title:'{N} au cirque', target:48, need:0, lvl:2.14, world:'trot',
    theme:{ sky:['#fecdd3','#fde68a'], ground:['#fcd34d','#f59e0b'], obstacle:'🎈',
      decos:[{e:'🎪',x:78,top:16,s:2.2},{e:'🎈',x:10,top:8,s:1.2},{e:'⭐',x:32,top:12,s:1},{e:'🎉',x:55,top:6,s:1}] },
    text:"Ce samedi, un cirque arrive au village avec des lumières partout. {N} regarde les acrobates qui volent sous le grand chapiteau rouge. Un clown rigolo lui offre un ballon jaune. {LeM} salue le public avec une belle révérence, et tout le monde applaudit très fort. {P} est {fiere} de {sonM}, une vraie star du cirque !" },
  { id:'plage', emoji:'🏖️', title:'{N} à la plage', target:50, need:2, lvl:2.21, world:'trot',
    theme:{ sky:['#7dd3fc','#e0f2fe'], ground:['#fde68a','#fbbf24'], obstacle:'🌊',
      decos:[{e:'☀️',x:88,top:5,s:1.6},{e:'⛵',top:22,s:1.2,drift:45},{e:'⛱️',x:8,top:28,s:1.7},{e:'🐚',x:60,bot:5,s:.9}] },
    text:"Cet été, {P} emmène {N} voir la mer pour la première fois. {LeM} pose une patte sur le sable chaud, puis {ilM} recule, {surprisM}. Une vague douce vient chatouiller ses jambes. {P} rit très fort. Ensemble, {ils} galopent le long de la plage, et le vent salé les décoiffe {tousD} les deux." },
  { id:'feuilles', emoji:'🍂', title:'La tempête de feuilles', target:52, need:4, lvl:2.29, world:'trot',
    theme:{ sky:['#fed7aa','#ffedd5'], ground:['#bef264','#84cc16'], obstacle:'🍁',
      decos:[{e:'🌳',x:82,top:20,s:2},{e:'🍁',top:8,s:1.1,drift:20},{e:'🍂',top:18,s:1,drift:28},{e:'🍂',x:14,bot:6,s:.9}] },
    text:"Cet automne, le vent souffle fort sur la ferme. Des feuilles rouges et dorées tourbillonnent dans le pré. {N} court après elles et saute pour les attraper. {P} ramasse un gros tas de feuilles, puis {leM} plonge dedans, très {contentM}. {Ils} jouent ainsi tout le reste de la journée." },

  /* ---------- Grand galop 🐎 ---------- */
  { id:'concours', emoji:'🏆', title:'Le grand concours', target:54, need:6, lvl:2.36, world:'grand-galop',
    theme:{ sky:['#7dd3fc','#bae6fd'], ground:['#86efac','#22c55e'], obstacle:'🌿',
      decos:[{e:'🚩',x:6,top:24,s:1.5},{e:'🚩',x:88,top:24,s:1.5},{e:'🏟️',x:44,top:8,s:1.4},{e:'👏',x:24,top:10,s:1}] },
    text:"Dimanche, le grand jour arrive enfin : le concours du club. {P} respire un grand coup, {el} a un peu peur. {N} avance vers le premier obstacle et saute très haut. Le public applaudit fort. À la fin du parcours, {P} reçoit un joli ruban bleu. {El} serre {sonM} dans ses bras car {ils} forment une belle équipe." },
  { id:'tresor', emoji:'🗺️', title:'Le trésor {duM} pirate', target:58, need:8, lvl:2.43, world:'grand-galop',
    theme:{ sky:['#93c5fd','#bfdbfe'], ground:['#fde68a','#f59e0b'], obstacle:'💰',
      decos:[{e:'🏴‍☠️',x:6,top:14,s:1.7},{e:'🦜',top:10,s:1.2,drift:26},{e:'⚓',x:84,bot:6,s:1.2},{e:'🌴',x:72,top:18,s:1.9}] },
    text:"Un matin, {P} trouve une vieille carte au fond de la grange. Elle montre un trésor caché près du grand chêne. {N} porte un foulard rouge, comme un vrai pirate. {Ils} suivent le chemin, passent le pont de bois et comptent dix pas. Sous la terre, {ils} découvrent un coffre rempli de pommes dorées !" },
  { id:'pluie', emoji:'🌈', title:'Après la pluie', target:60, need:10, lvl:2.5, world:'grand-galop',
    theme:{ sky:['#cbd5e1','#e2e8f0'], ground:['#86efac','#4ade80'], obstacle:'🐸',
      decos:[{e:'🌈',x:58,top:6,s:2.4},{e:'☁️',top:5,s:1.5,drift:40},{e:'💧',x:20,top:26,s:1},{e:'🌷',x:10,bot:5,s:1}] },
    text:"La pluie tambourine sur le toit de la grange depuis ce matin. {N} attend, le nez collé à la fenêtre. Enfin, le soleil revient et un arc de couleurs géant traverse le ciel. {P} monte en selle, et {ils} partent chercher le bout du fameux arc. {Ils} ne le trouvent pas, mais {ils} découvrent une mare pleine de grenouilles rigolotes." },
  { id:'neige', emoji:'❄️', title:'La neige magique', target:62, need:12, lvl:2.57, world:'grand-galop',
    theme:{ sky:['#e0f2fe','#f8fafc'], ground:['#f1f5f9','#cbd5e1'], obstacle:'❄️',
      decos:[{e:'⛄',x:82,bot:6,s:1.8},{e:'❄️',top:8,s:1,drift:24},{e:'❄️',top:22,s:1.2,drift:36},{e:'🌨️',x:10,top:6,s:1.3}] },
    text:"Ce matin, la ferme est toute blanche. La neige tombe doucement du ciel gris. {N} souffle des petits nuages de vapeur avec son nez. {P} lance une boule de neige, et {leM} saute pour la toucher du bout du museau. Ensuite, {ils} dessinent des traces rigolotes dans la poudre blanche, puis {ils} rentrent bien au chaud." },
  { id:'montagne', emoji:'⛰️', title:'Le sommet de la montagne', target:64, need:15, lvl:2.64, world:'grand-galop',
    theme:{ sky:['#bfdbfe','#dbeafe'], ground:['#d6d3d1','#a8a29e'], obstacle:'🪨',
      decos:[{e:'🏔️',x:8,top:10,s:2.2},{e:'⛰️',x:68,top:14,s:2},{e:'🦅',top:8,s:1.2,drift:30},{e:'🌲',x:44,top:28,s:1.3}] },
    text:"Cet hiver, {P} et {N} partent en randonnée vers la grande montagne. Le sentier monte, tourne, et devient de plus en plus raide. {LeM} avance à petits pas prudents entre les rochers gris. Tout en haut, la vue est magnifique : les maisons du village ressemblent à des jouets minuscules. {P} crie de joie, et la montagne répond en écho." },

  /* ---------- Champion 🏆 ---------- */
  { id:'fee', emoji:'🧚', title:'La fée des chevaux', target:66, need:18, lvl:2.71, world:'champion',
    theme:{ sky:['#c4b5fd','#e9d5ff'], ground:['#86efac','#4ade80'], obstacle:'🌸',
      decos:[{e:'🌙',x:86,top:6,s:1.6},{e:'✨',x:20,top:12,s:1.1},{e:'⭐',x:46,top:8,s:1},{e:'🦋',top:20,s:1,drift:34}] },
    text:"Cette nuit, une fée entre sans bruit dans la petite écurie. Elle touche doucement {N} sur la tête avec sa baguette magique. {LeM} brille comme une étoile et des ailes dorées poussent sur son dos. {IlM} vole très haut dans le ciel plein de nuages roses. Au matin, {P} trouve une plume dorée posée sur la paille." },
  { id:'poulain', emoji:'🐣', title:'Le petit poulain', target:68, need:21, lvl:2.79, world:'champion',
    theme:{ sky:['#fbcfe8','#fce7f3'], ground:['#bbf7d0','#86efac'], obstacle:'🌼',
      decos:[{e:'☀️',x:88,top:5,s:1.5},{e:'🌷',x:10,bot:5,s:1.1},{e:'🌼',x:68,bot:6,s:1},{e:'🦋',top:14,s:1,drift:30}] },
    text:"Une grande nouvelle attend {P} à la ferme : un poulain est né cette nuit ! Il tient à peine sur ses longues jambes fragiles. {N} le pousse doucement du museau pour le rassurer. Le bébé fait trois pas, tombe sur la paille, puis se relève courageusement. {P} lui choisit un joli nom : Noisette." },
  { id:'dragon', emoji:'🐉', title:'Le dragon gentil', target:70, need:24, lvl:2.86, world:'champion',
    theme:{ sky:['#a7f3d0','#d1fae5'], ground:['#4ade80','#15803d'], obstacle:'🔥',
      decos:[{e:'🌲',x:6,top:18,s:2},{e:'🌲',x:84,top:20,s:1.8},{e:'✨',x:50,top:10,s:1},{e:'🍎',x:64,bot:5,s:.9}] },
    text:"Au fond de la forêt vit un petit dragon vert nommé Pistache. Il est triste car tout le monde a peur de lui. {N} avance doucement et lui offre une pomme. Le dragon sourit, et une petite flamme de joie sort de son nez. Depuis ce jour, Pistache garde la ferme la nuit, et il réchauffe la paille en hiver." },
  { id:'etoiles', emoji:'🌠', title:'La nuit des étoiles', target:74, need:27, lvl:2.93, world:'champion',
    theme:{ sky:['#1e3a8a','#312e81'], ground:['#14532d','#052e16'], obstacle:'⭐',
      decos:[{e:'🌙',x:86,top:6,s:1.7},{e:'⭐',x:15,top:10,s:1},{e:'⭐',x:40,top:18,s:.8},{e:'🌠',top:8,s:1.3,drift:18},{e:'⭐',x:64,top:6,s:1.1}] },
    text:"Ce soir, {P} installe une grande couverture dans le pré, et {N} se couche tout près. Le ciel est rempli de milliers de points brillants. Soudain, une étoile filante traverse la nuit comme une flèche de lumière. {P} ferme les yeux et fait un vœu secret. {LeM} pose sa tête douce contre son épaule. Ensemble, {ils} comptent les étoiles très tard dans la nuit." },
  { id:'reve', emoji:'🚀', title:'Un rêve dans les nuages', target:78, need:30, lvl:3, world:'champion',
    theme:{ sky:['#312e81','#6d28d9'], ground:['#ede9fe','#c4b5fd'], obstacle:'🪐',
      decos:[{e:'🪐',x:12,top:10,s:1.6},{e:'🌟',x:44,top:6,s:1.2},{e:'☄️',top:12,s:1.3,drift:16},{e:'🌙',x:82,top:8,s:1.5}] },
    text:"Cette nuit, {N} fait un rêve extraordinaire. {IlM} porte un casque brillant et flotte doucement au milieu des planètes colorées. Les étoiles dansent tout autour comme des lucioles géantes. {IlM} rebondit sur la lune, {legerM} comme une plume, et salue une comète pressée. Au réveil, {leM} observe longtemps le ciel du matin, comme pour garder un morceau de son rêve." },

  /* ---------- Cavalier émérite 🎖️ (ex-CM1 v11) · lvl 3,2 → 3,9 ---------- */
  { id:'cm1-orage', emoji:'⛈️', title:'La nuit de la tempête', target:72, need:33, lvl:3.2, world:'emerite',
    theme:{ sky:['#475569','#64748b'], ground:['#365314','#1a2e05'], obstacle:'⚡',
      decos:[{e:'⛈️',x:14,top:6,s:1.6},{e:'☁️',top:10,s:1.5,drift:22},{e:'🌧️',x:60,top:12,s:1.3},{e:'🌾',x:8,bot:5,s:1}] },
    text:"Depuis le matin, de gros nuages sombres roulent dans le ciel de la ferme. Le vent se lève, les volets claquent, et les poules courent se cacher dans leur abri. {P} décide de rentrer {N} avant la pluie. Soudain, un éclair déchire le ciel et le tonnerre gronde comme un tambour géant. {LeM} tremble un peu, alors {P} pose une main douce sur son cou et lui parle calmement. Ensemble, {ils} traversent la cour sous les premières gouttes. Dans la grange, bien au sec, {ils} écoutent la pluie danser sur le toit. {N} pose sa tête contre {P}, {rassureM}, et la tempête devient presque une musique." },
  { id:'cm1-course', emoji:'🏇', title:'La course des collines', target:78, need:37, lvl:3.34, world:'emerite',
    theme:{ sky:['#7dd3fc','#bae6fd'], ground:['#fde047','#eab308'], obstacle:'🌾',
      decos:[{e:'🚩',x:8,top:22,s:1.4},{e:'🚩',x:88,top:22,s:1.4},{e:'⛅',top:8,s:1.3,drift:34},{e:'🌾',x:42,bot:5,s:1}] },
    text:"Ce dimanche, tout le village se retrouve pour la grande course des collines. Des cavaliers venus de partout ajustent leurs casques et vérifient leurs selles. Au signal, {N} bondit comme une flèche. Le chemin monte entre les champs dorés, plonge dans un petit bois, puis longe la rivière qui scintille. {P} se penche en avant et encourage {sonM} de la voix. Dans le dernier virage, {ils} dépassent deux concurrents étonnés. La ligne est là, toute proche. Un dernier effort, un grand saut final, et {ils} franchissent la ligne les {premiersD} ! La foule applaudit longtemps, et {N} salue avec panache." },
  { id:'cm1-chouette', emoji:'🦉', title:'La chouette blanche', target:84, need:41, lvl:3.48, world:'emerite',
    theme:{ sky:['#1e293b','#334155'], ground:['#14532d','#052e16'], obstacle:'🌿',
      decos:[{e:'🦉',x:78,top:14,s:1.6},{e:'🌲',x:8,top:18,s:2},{e:'🌲',x:30,top:22,s:1.6},{e:'🌕',x:60,top:6,s:1.2}] },
    text:"Un soir, {P} rentre tard par le sentier de la forêt. La lumière baisse, les ombres des arbres deviennent longues et mystérieuses. Une chouette blanche se pose alors sur une branche basse et hulule doucement, comme pour dire bonjour. Chaque fois que {leM} avance, la chouette vole un peu plus loin et attend. {P} comprend que la chouette montre le chemin. {Ils} suivent leur guide entre les fougères, passent un vieux tronc couché, et retrouvent enfin la lumière chaude de la ferme. Avant de partir, la chouette fait trois grands cercles dans le ciel étoilé. {P} promet de revenir la saluer, et {N} hoche la tête, comme pour promettre aussi." },
  { id:'cm1-riviere', emoji:'🌉', title:'La rivière en colère', target:90, need:45, lvl:3.62, world:'emerite',
    theme:{ sky:['#bfdbfe','#dbeafe'], ground:['#60a5fa','#2563eb'], obstacle:'🪨',
      decos:[{e:'🌉',x:12,top:16,s:1.8},{e:'🌊',top:26,s:1.1,drift:30},{e:'🪨',x:70,bot:6,s:1},{e:'🌲',x:88,top:20,s:1.5}] },
    text:"Au printemps, la rivière déborde et emporte le petit pont de bois. De ce côté, impossible de rejoindre le village pour la fête. {P} observe le courant, réfléchit, puis remarque un endroit où la rivière devient large et peu profonde. Prudemment, {N} entre dans la rivière fraîche, un pas après un autre. Les cailloux roulent sous ses pattes, mais {ilM} garde son calme et son équilibre. Au milieu, le courant pousse plus fort, alors {P} serre les jambes et garde le cap. {Ils} atteignent enfin la rive opposée, avec une grande fierté. Au village, tout le monde applaudit les {herosD} du jour, et la fête peut commencer." },
  { id:'cm1-phare', emoji:'🗼', title:'La lumière du phare', target:95, need:50, lvl:3.76, world:'emerite',
    theme:{ sky:['#fda4af','#fecdd3'], ground:['#fde68a','#fbbf24'], obstacle:'🌊',
      decos:[{e:'🗼',x:84,top:8,s:2},{e:'⛵',top:22,s:1.2,drift:40},{e:'🌅',x:10,top:8,s:1.5},{e:'🐚',x:40,bot:5,s:.9}] },
    text:"Cet été, {P} et {N} découvrent un vieux phare posé au bout de la falaise. Le gardien, un vieil homme au sourire doux, raconte que la lampe ne fonctionne plus depuis des semaines. Or, ce soir, un bateau de pêcheurs doit rentrer au port dans la nuit noire. {P} propose son aide aussitôt. Ils montent ensemble le grand escalier en colimaçon, portent la nouvelle ampoule, et resserrent chaque vis avec patience. Quand la nuit tombe, une immense lumière balaie enfin la mer. Au loin, le bateau répond par trois coups de corne joyeux. Le gardien serre la main à {P}, caresse doucement {N}, et leur offre le plus beau des mercis : un coucher de soleil depuis le sommet du phare." },
  { id:'cm1-aurore', emoji:'🌌', title:'Les lumières du nord', target:100, need:55, lvl:3.9, world:'emerite',
    theme:{ sky:['#0f172a','#1e1b4b'], ground:['#f1f5f9','#cbd5e1'], obstacle:'❄️',
      decos:[{e:'🌌',x:20,top:6,s:1.6},{e:'⭐',x:60,top:10,s:1},{e:'🌠',top:8,s:1.2,drift:18},{e:'❄️',x:80,top:20,s:1}] },
    text:"Une légende raconte que, une nuit par an, le ciel du nord se remplit de couleurs dansantes. Cette nuit est arrivée. {P} prépare deux couvertures chaudes, un thermos de chocolat, et guide {N} vers le sommet de la colline. Le froid pique les joues, mais le spectacle mérite chaque pas. Vers minuit, un premier ruban vert ondule entre les étoiles, puis un voile rose, puis un fleuve violet qui traverse tout le ciel. {N} lève la tête, {fascineM}, les yeux remplis de lumière. {P} murmure que certaines merveilles se méritent avec de la patience. {Ils} restent là longtemps, dans un silence heureux, pendant que le ciel peint pour {eux} le plus beau tableau du monde." }
];
